Feature number of unseen comments
PewePro/alef-tng pull request #211
Opened 2017-02-25 10:37 UTC by veronikagondova

2017-02-25 21:01 UTC, petergaspar requested changes

2017-02-25 21:01 UTC, petergaspar commented on app/models/feedback.rb
> +    self.learning_object.increment!(:comment_number, by = 1)
- navrhujem premenovat stlpec -- vyssie sa pouziva `feedback` a tu zrazu `comment`
- parameter `by = 1` nie je potrebny, staci `self.learning_object.increment!(:comment_number)`

2017-02-25 21:01 UTC, petergaspar commented on app/models/feedback.rb
> +    newest_comment = self.learning_object.feedbacks.where('visible = True').order(created_at: :desc).first
aky je vyznam tejto metody, celkom tomu neviem prist na zubok?

2017-02-25 21:01 UTC, petergaspar commented on app/views/weeks/show.html.erb
> +            <% if lo.last_comment_time.present? && last_inter.present? &&
vo view sa odohrava neprimerane vela Rails kodu. Toto by som skusil este nejako prekopat tak, aby vo view bola iba podmienka na styl, ze ci je novy komentar.

2017-02-25 21:01 UTC, petergaspar commented on Gemfile
> +gem 'bulk_insert'
toto sa kde pouziva?

2017-02-25 21:22 UTC, veronikagondova commented on Gemfile
> +gem 'bulk_insert'
uz nikde.. zmazem

2017-04-14 12:33 UTC, petergaspar commented on app/models/learning_object.rb
> +  def has_new_feedback(last_inter, last_comment)
`has_new_feedback?` (nazov funkcie vracajuci `boolean` by mal mat otaznik)

2017-04-14 12:33 UTC, petergaspar commented on app/models/learning_object.rb
> +  def has_new_feedback(last_inter, last_comment)
co je to `last_inter`? last interaction? uplne v pohode mozes nazvat premennu celym menom `last_interaction`

2017-04-14 12:33 UTC, petergaspar commented on app/views/weeks/show.html.erb
> +            if lo_status == "only_seen"
tychto tisic if-ov sa da vyriesit velmi elegantne, ak texty umiestnis do prekladov (https://github.com/PewePro/alef-tng/blob/master/config/locales/sk.yml) a vysledok premennej `lo_status` sa tak prejavi priamo v HTML kode
```
<i class="icon-#{lo_status}"></i> #{t('XXX.' + lo_status)}
```

2017-04-14 12:33 UTC, petergaspar commented on app/models/learning_object.rb
> +    current_lo_info = los_info.find {|r| r["result_id"] == self.id.to_s}
co robi toto? chybaju mi v kode komentare

2017-04-14 16:43 UTC, petergaspar approved these changes

2017-04-14 16:44 UTC, merged